Build release without zip to prevent windows defender flag
Build release without zip to prevent windows defender flag

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -55,16 +55,18 @@ jobs:
       - name: Remove any pdb files
         run: Get-ChildItem publish -Recurse -Include *.pdb | Remove-Item -Force -ErrorAction SilentlyContinue
 
-      - name: Zip artifact
+      - name: Verify exe
         run: |
-          Compress-Archive -Path publish/win-x64-fdd/* -DestinationPath "$env:APP_NAME-framework-dependent-win-x64.zip"
+          if (-not (Test-Path "publish/win-x64-fdd/$env:APP_NAME.exe")) { Write-Error 'EXE not found'; exit 1 }
+          Get-Item "publish/win-x64-fdd/$env:APP_NAME.exe" | Format-List *
 
-      - name: Upload artifact
+      - name: Upload exe artifact (no zip)
         uses: actions/upload-artifact@v4
         with:
           name: ${{ env.APP_NAME }}-framework-dependent-win-x64
-          path: ${{ env.APP_NAME }}-framework-dependent-win-x64.zip
+          path: publish/win-x64-fdd/${{ env.APP_NAME }}.exe
           if-no-files-found: error
+          compression-level: 0
 
   release:
     if: startsWith(github.ref, 'refs/tags/v')
@@ -79,7 +81,7 @@ jobs:
         uses: softprops/action-gh-release@v2
         with:
           files: |
-            dist/**/iptv-desktop-browser-framework-dependent-win-x64.zip
+            dist/**/iptv-desktop-browser.exe
           draft: false
           prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
         env:
